apiVersion: v1
kind: Secret
metadata:
  name: ethos-go-secret
  namespace: ethos-go
type: Opaque
stringData:
  DB_PASSWORD: "ethosgo"
  POSTGRES_PASSWORD: "ethosgo"
  AUTH_JWT_SECRET: "super-secret-key-that-is-at-least-32-chars-long"
  SMTP_PASSWORD: "tpld sltq hivm wxcj"
