apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethos-go-worker
  namespace: ethos-go
  labels:
    app: ethos-go-worker
spec:
  selector:
    matchLabels:
      app: ethos-go-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: ethos-go-worker
    spec:
      containers:
      - name: worker
        image: sammidev/ethos-go:latest
        imagePullPolicy: IfNotPresent
        command: ["/ethos-worker"]
        envFrom:
        - configMapRef:
            name: ethos-go-config
        - secretRef:
            name: ethos-go-secret
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 256Mi
